# Generated by Django 3.2.5 on 2021-07-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_crawl', models.DateField(verbose_name='date crawled')),
                ('date_publish', models.DateField(verbose_name='date published')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('alt', models.TextField()),
                ('img_url', models.URLField()),
            ],
        ),
    ]
